### ISSUE TITLE
Question : Comment stocker simplement un tableau d'une taille indeterminé dans une table sql?

### ISSUE THREAD

**Issue by marcus-timtow** [Saerer/plateau_argent#1]
un tableau c'est a dire, une ligne contenant un tableau d'entier par exemple, sauf qu'on ne connait pas forcement sa taille a l'avance( il pourrait y en avoir de 36 elements ou de 400), meme si il avait tout le temps la meme taille, j'ose esperer qu'il existe un moyen plus simple que de créer au prealable les 400 colones a l'avance non?

EDIT : il semble  avoir une solution avec les foreign key, mais j'ai pas la maitrise suffisante du sql,
....doooonnc, je vais reprendre un cours sur le sql, en plus on en aurat besoin pour faire un peut d'optimisation le jour ou il y aurat 3millions d'utilisateurs mouhahaha !!!

**Comment by marcus-timtow** [comment]
on aurat besoins de ca car un plateau de jeu contient un nombre indeterminé de case, donc un tableau de taille indeterminée d'objet, d'ou la merde...

**Comment by Saerer** [comment]
Mais ouai, je suis entrain de regarder le sql sur wikibooks

**Comment by marcus-timtow** [comment]
tuto : http://www.tutorialspoint.com/sql/index.htm
tuto : https://openclassrooms.com/courses/administrez-vos-bases-de-donnees-avec-mysql
tuto : http://www.1keydata.com/sql/sql.html
tuto : http://sqlzoo.net/
wiki : https://en.wikipedia.org/wiki/SQL
wikibook : https://fr.wikibooks.org/wiki/Programmation_SQL
pour pratiquer le sql sans rien installer : http://www.tutorialspoint.com/oracle_terminal_online.php
exercices : https://en.wikibooks.org/wiki/SQL_Exercises

**Comment by Saerer** [comment]
Nickel thx

**Comment by marcus-timtow** [comment]
Ca pourra être pas mal de lire ca après : http://www.1keydata.com/database-normalization/

**Comment by Saerer** [comment]
http://fadace.developpez.com/sgbdcmp/

**Comment by marcus-timtow** [comment]
https://blogs.oracle.com/GeorgeTrujillo/entry/mysql_versus_oracle_features_functionality

**Comment by Saerer** [comment]
regarde moi ça MTT ! http://vogella.developpez.com/tutoriels/android/utilisation-base-donnees-sqlite/#LIII-A

**Comment by marcus-timtow** [comment]
ouaip, ou alors regarde le tuto du site du zero sur la prog android, dans la section sql y'a un truc pas mal avec les helper aussi :)

**Comment by marcus-timtow** [comment]
Ce que je sais pas faire par contre c'est me connecter a une db exterieure (sur un server) depuis android, tu sais comment on fait?

**Comment by marcus-timtow** [comment]
https://openclassrooms.com/courses/gestion-de-verrou-mysql
